### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by cfvescovo**

### CODE REVIEW

**Comment by cfvescovo** [comment]
The latest version of selectors (0.23.0) requires LocalName to implement the trait ToCss (from cssparser) but the LocalName type provided by html5ever (the one we are currently using) does not implement that trait.
As we cannot implement a trait from an external crate on a type provided by an external crate, we have to create our own struct that wraps LocalName and implements ToCss. 
However, as noted in #45, using LocalName is not the best solution as far as performance is concerned. Should we make the switch and use Strings (or something else) instead of LocalNames?
@teymour-aldridge What is your opinion on this?

**Comment by teymour-aldridge** [comment]
Could we submit a patch to the Servo project to implement ToCss?

**Comment by cfvescovo** [comment]
Yes. However, what is your opinion on the performance concerns expressed in #45?

**Comment by cfvescovo** [comment]
I looked at the implementation of LocalName ([code](https://github.com/servo/html5ever/blob/master/markup5ever/build.rs#L38-L49)): I think we cannot directly impl any trait on a type generated at compile-time by string_cache. We could impl ToCss on Atoms (in the string_cache crate) but I don't think this change would be accepted.

**Comment by cfvescovo** [comment]
@teymour-aldridge What do you think about switching to Strings?

**Comment by cfvescovo** [comment]
Since implementing ToCss for LocalNames seems unfeasible, I do not think we have other alternatives.

**Comment by teymour-aldridge** [comment]
Yeah, it would be interesting if we had some benchmarks (maybe we could borrow some of Cloudflare's – https://github.com/cloudflare/lol-html) to compare.

**Comment by teymour-aldridge** [comment]
But I agree that it seems to be the only way forwards.

**Comment by cfvescovo** [comment]
@teymour-aldridge I will set this pull request as ready and, if you agree, I will merge it as it is now

**Comment by cfvescovo** [comment]
I see there are some warnings, I will fix them asap

**Comment by Corfucinas** [comment]
Good job with this crate, I will use it now for a project

**Comment by teymour-aldridge** [comment]
Sorry for not getting back to you promptly. Looks good.

**Pull request merged**
